# Quickstart : fill the BETTER_AUTH_SECRET variable (see below) and you're good to go !
services:
  kan:
    image: ghcr.io/kanbn/kan:latest
    ports:
      - 3000:3000
    environment:
      # SEE https://github.com/kanbn/kan?tab=readme-ov-file#environment-variables-
      - BETTER_AUTH_SECRET=  # Random 32+ char string, can generate with: tr -dc A-Za-z0-9 </dev/urandom | head -c 32; echo
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_ALLOW_CREDENTIALS=true
      - NEXT_PUBLIC_DISABLE_SIGN_UP=false
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/kan

      # Optional email settings
      #- EMAIL_FROM=  # Example: "Kan <hello@mail.kan.bn>"
      #- SMTP_HOST=
      #- SMTP_PORT=465 # Port 587 will not work
      #- SMTP_USER=
      #- SMTP_PASSWORD=
      #- BETTER_AUTH_TRUSTED_ORIGINS=http://localhost:3000
    depends_on:
      - postgres
    command: sh -c "cd /app && pnpm db:migrate && cd /app/apps/web && pnpm start"
    restart: unless-stopped
    networks:
      - kan_network
      
  postgres:
    image: postgres:15
    container_name: kan-db
    environment:
      - POSTGRES_DB=kan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - kan_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - kan_network
      
volumes:
  kan_postgres_data:
networks:
  kan_network: 
